[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

; USB CDC on Boot: enables Serial output over native USB port
build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D CORE_DEBUG_LEVEL=3

lib_deps = 
    lovyan03/LovyanGFX @ ^1.1.16
    h2zero/NimBLE-Arduino @ ^1.4.2
